title: DeepSpeed
email: deepspeed@microsoft.com
description: >-
  DeepSpeed is a deep learning optimization library that makes distributed
  training easy, efficient, and effective.

locale : "en-US"

repository: microsoft/DeepSpeed
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.deepspeed.ai" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.19.0"
minimal_mistakes_skin : "air"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

#paginate: 10
#paginate_path: /blog/page:num

include: ["_pages"]
exclude: ["code-docs"]

collections:
  tutorials:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: false
  # _tutorials
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single
      toc: true
      toc_label: "Contents"
      sidebar:
        nav: "lnav"

timezone: America/Los_Angeles
breadcrumbs: true
