name: IntegrateFromUpstream
on:
#  schedule:
#    # verified via crontab.guru website. “At 06:55 on Monday.”
#    - cron: '55 6 * * 1'
  workflow_dispatch:
    inputs:
      message:
        description: 'Reason for manual trigger'
        required: false
        default: 'refresh master'
jobs:
  IntegrateFromUpstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Fetch and Merge
        run: |
          echo "Reason for trigger: ${{ github.event.inputs.message }}"
          echo "Actor for trigger: ${{ github.actor }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add upstream https://github.com/microsoft/DeepSpeed
          git fetch upstream master
          git merge upstream/master 
          # Since we use our own fork of DeepSpeedExamples, ignore theirs
          git checkout HEAD DeepSpeedExamples
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
#          token: ${{ secrets.PAT }}
          branch: IFU-${{ steps.extract_branch.outputs.branch }}-${{ steps.date.outputs.date }}
          title: IFU-${{ steps.extract_branch.outputs.branch }}-${{ steps.date.outputs.date }}
          assignees: rraminen
