name: IntegrateFromUpstream
on:
#  schedule:
#    # verified via crontab.guru website. “At 06:55 on Monday.”
#    - cron: '55 6 * * 1'
  workflow_dispatch:
    inputs:
      message:
        description: 'Reason for manual trigger'
        required: false
        default: 'refresh branch'
jobs:
  IntegrateFromUpstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Fetch and Merge
        id: fetch_and_merge
        run: |
          echo "Reason for trigger: ${{ github.event.inputs.message }}"
          echo "Actor for trigger: ${{ github.actor }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add upstream https://github.com/microsoft/DeepSpeed
          git fetch upstream master
          git merge upstream/master 
          # Since we use our own fork of DeepSpeedExamples, ignore theirs
          git checkout HEAD DeepSpeedExamples
      - name: Create Pull Request
        id: create_pull_request
        uses: jithunnair-amd/create-pull-request@v3
        with:
#          token: ${{ secrets.PAT }}
          branch: IFU-${{ steps.extract_branch.outputs.branch }}-${{ steps.date.outputs.date }}
          title: IFU-${{ steps.extract_branch.outputs.branch }}-${{ steps.date.outputs.date }}
          assignees: rraminen
          reviewers: jithunnair-amd
          delete-branch: true
      - name: Send email
        uses: jithunnair-amd/action-send-mail@v3.1.0
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: IFU to ${{ steps.extract_branch.outputs.branch }} branch of ${{ github.repository }}
          to: Jithun.Nair@amd.com, RamyaSai.Ramineni@amd.com
          from: ${{ secrets.GMAIL_USERNAME }}
          html_body: |
            <b>Fetch and Merge</b>: ${{ steps.fetch_and_merge.outcome }} <br/>
            <b>Create Pull Request</b>: ${{ steps.create_pull_request.outcome }} <br/>
            <b>Pull request</b>: <a href="${{ steps.create_pull_request.outputs.pull-request-url }}">${{ steps.create_pull_request.outputs.pull-request-url }}</a> <br/>
